version: 2.1

jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: node:14.4.0
    steps:
      - checkout
      - restore_cache:
          key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          command: |
            if [ "${CIRCLE_BRANCH}" != "main" ]; then
              circleci step halt
            fi
      - run: echo "deploy start"
      - run: yarn build
      - run: git config --global user.email "ikmiyabi@users.noreply.github.com"
      - run: git config --global user.name "circleci"
      - run: git checkout deploy
      - run: rm -rf docs
      - run: mv dist/ docs/
      - run: git add -A
      - run: git commit -m "[ci skip] deploy"
      - run: git push -f origin deploy
      - run: echo "deploy end"
